debug = true
[site]
prefix = "/daily"
title = "阿Q的博客"
about = """
**这是一个多行文本示例。**

你可以在这里写博客的简介，

支持换行和特殊字符。

---

## 标题

"""
twitter = "https://twitter.com/enumapp"
github = "https://github.com/livepo"
[mysql]
host = "127.0.0.1"
port = 3306
user = "root"
password = "123456"
database = "lazyblog"
[auth]
XAdminToken = "xxx"
